stages:
  - build

build-netbox-image:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  variables:
    TAG: v4.5.6-plugins-${CI_COMMIT_SHORT_SHA}
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY -u gitlab-ci-token --password-stdin
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}/netbox-custom:${TAG} -f netbox/docker/Dockerfile netbox/docker
    - docker push ${CI_REGISTRY_IMAGE}/netbox-custom:${TAG}
  rules:
    - changes:
        - netbox/docker/Dockerfile