image:
  registry: gitlab.lst.tfo.upm.es:4567
  repository: kubernetescore/aplicacionescore/netbox-custom
  tag: v4.5.6-plugins-462cb8cc
  pullPolicy: IfNotPresent
  pullSecrets:
    - netbox-registry-creds

containerPort: 8080

service:
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 500m
    memory: 1536Mi
  limits:
    cpu: 1000m
    memory: 3Gi

extraVolumes:
  - name: internal-ca
    configMap:
      name: netbox-internal-ca

extraVolumeMounts:
  - name: internal-ca
    mountPath: /etc/ssl/certs/step-ca.crt
    subPath: ca.crt
    readOnly: true

extraEnvs:
  - name: GRANIAN_WORKERS
    value: "2"
  - name: GRANIAN_EXTRA_ARGS
    value: "--host=0.0.0.0"
  - name: SERVER_HOST
    value: "0.0.0.0"
  - name: ALLOWED_HOSTS
    value: "netbox.fluffy.lst"
  - name: CSRF_TRUSTED_ORIGINS
    value: "https://netbox.fluffy.lst"
  - name: USE_X_FORWARDED_HOST
    value: "true"
  - name: REQUESTS_CA_BUNDLE
    value: "/etc/ssl/certs/step-ca.crt"

postgresql:
  enabled: false

externalDatabase:
  host: "netbox-postgres-svc.netbox.svc.cluster.local"
  port: 5432
  database: "netbox"
  username: "netbox"
  password: "RKE2admin2026"

redis:
  enabled: false
  host: "netbox-redis-svc.netbox.svc.cluster.local"
  port: 6379
  password: "RKE2admin2026"

tasksRedis:
  host: "netbox-redis-svc.netbox.svc.cluster.local"
  port: 6379
  password: "RKE2admin2026"

cachingRedis:
  host: "netbox-redis-svc.netbox.svc.cluster.local"
  port: 6379
  password: "RKE2admin2026"

startupProbe:
  enabled: false
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

secretKey: "RSWSq+RaeBvZuodVBUK3tB3e7P0SemCiaDcIQMwQLVw/MLQRpbc="

persistence:
  enabled: true
  existingClaim: "netbox-media-v2"

ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: "step-ca-issuer"
    traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: netbox.fluffy.lst
      paths:
        - /
  tls:
    - secretName: netbox-tls
      hosts:
        - netbox.fluffy.lst

remoteAuth:
  enabled: false

extraConfig:
  - values:
      AUTHENTICATION_BACKENDS:
        - 'social_core.backends.open_id_connect.OpenIdConnectAuth'
        - 'netbox.authentication.ModelBackend'

      REMOTE_AUTH_ENABLED: true
      REMOTE_AUTH_BACKEND: 'social_core.backends.open_id_connect.OpenIdConnectAuth'

      SOCIAL_AUTH_OIDC_OIDC_ENDPOINT: 'https://keycloak.fluffy.lst/realms/Nutty'
      SOCIAL_AUTH_OIDC_KEY: 'netbox'
      SOCIAL_AUTH_OIDC_SECRET: 'bfUDd69F4QNxxDYqCPDdKWrP5IrOELCT'
      SOCIAL_AUTH_OIDC_SCOPE:
        - openid
        - profile
        - email

      SECURE_PROXY_SSL_HEADER:
        - HTTP_X_FORWARDED_PROTO
        - https

      PLUGINS:
        - 'netbox_attachments'
        - 'netbox_topology_views'
        - 'netbox_secrets'
        - 'netbox_reorder_rack'
        - 'netbox_lists'
        - 'netbox_inventory'
        - 'netbox_custom_objects'
        - 'validity'
        - 'netbox_dns'