apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-gitops
  namespace: argocd
spec:
  project: default
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://codecentric.github.io/helm-charts
      chart: keycloakx
      targetRevision: "7.2.0"
      helm:
        valueFiles:
          - $values/keycloak/values.yaml
    - repoURL: https://gitlab.lst.tfo.upm.es/kubernetescore/aplicacionescore.git
      targetRevision: main
      ref: values
    - repoURL: https://gitlab.lst.tfo.upm.es/kubernetescore/aplicacionescore.git
      targetRevision: main
      path: keycloak/manifests/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true