apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-gitops
  namespace: argocd
spec:
  project: default
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: keycloak
      targetRevision: "22.1.2"
      helm:
        valueFiles:
          - $values/keycloak/values.yaml
    - repoURL: https://gitlab.lst.tfo.upm.es/kubernetescore/aplicacionescore.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true