auth:
  adminUser: admin
  adminPassword: "RKE2admin2026"

postgresql:
  enabled: false

externalDatabase:
  host: "keycloak-postgres-svc.keycloak.svc.cluster.local"
  port: 5432
  user: "keycloak"
  database: "keycloak"
  password: "RKE2admin2026"

ingress:
  enabled: true
  ingressClassName: "traefik"
  hostname: keycloak.fluffy.lst
  annotations:
    cert-manager.io/cluster-issuer: "step-ca-issuer"
    traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
  tls: true
  extraSecrets:
    - name: keycloak-tls
      hosts:
        - keycloak.fluffy.lst

resources:
  limits:
    memory: 1024Mi
  requests:
    cpu: 250m
    memory: 512Mi