image:
  repository: quay.io/keycloak/keycloak
  tag: "25.0.4"

replicas: 1

command:
  - "/opt/keycloak/bin/kc.sh"
args:
  - "start"
  - "--http-enabled=true"
  - "--http-port=8080"
  - "--hostname-strict=false"
  - "--proxy=edge"
  - "--health-enabled=true"

extraEnv: |
  - name: KEYCLOAK_ADMIN
    value: "admin"
  - name: KEYCLOAK_ADMIN_PASSWORD
    value: "RKE2admin2026"
  - name: KC_DB
    value: postgres
  - name: KC_DB_URL_HOST
    value: keycloak-postgres-svc.keycloak.svc.cluster.local
  - name: KC_DB_URL_PORT
    value: "5432"
  - name: KC_DB_USERNAME
    value: keycloak
  - name: KC_DB_PASSWORD
    value: "RKE2admin2026"
  - name: KC_DB_URL_DATABASE
    value: keycloak

startupProbe: |
  httpGet:
    path: /health/started
    port: 9000
    scheme: HTTP
  initialDelaySeconds: 15
  timeoutSeconds: 1
  failureThreshold: 60
  periodSeconds: 5

readinessProbe: |
  httpGet:
    path: /health/ready
    port: 9000
    scheme: HTTP
  initialDelaySeconds: 10
  timeoutSeconds: 1

livenessProbe: |
  httpGet:
    path: /health/live
    port: 9000
    scheme: HTTP
  initialDelaySeconds: 10
  timeoutSeconds: 1

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: "step-ca-issuer"
    traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
  rules:
    - host: keycloak.fluffy.lst
      paths:
        - path: /
  tls:
    - hosts:
        - keycloak.fluffy.lst
      secretName: keycloak-tls

resources:
  limits:
    memory: 1024Mi
  requests:
    cpu: 250m
    memory: 512Mi