apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-gitops
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 33.0.0
      helm:
        valueFiles:
          - $values/traefik/values.yaml

    - repoURL: xxx
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true