apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-media-v2
  namespace: netbox
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
