global:
  enabled: true
  tlsDisable: true

injector:
  enabled: true

server:
  enabled: true
  replicas: 1

  dataStorage:
    enabled: true
    size: 2Gi
    storageClass: "longhorn"
    accessMode: ReadWriteOnce

  ingress:
    enabled: true
    ingressClassName: "traefik"
    pathType: Prefix
    annotations:
      cert-manager.io/cluster-issuer: "step-ca-issuer"
      traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - host: vault.fluffy.lst
        paths:
          - /
    tls:
      - secretName: vault-tls
        hosts:
          - vault.fluffy.lst

  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address     = "[::]:8200"
        cluster_address = "[::]:8201"
      }

      storage "raft" {
        path = "/vault/data"
      }