apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: step-ca-gitops
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: xxx
      chart: step-certificates
      targetRevision: 1.25.2
      helm:
        valueFiles:
          - $values/step-ca/values.yaml

    - repoURL: xxx
      targetRevision: HEAD
      ref: values

    - repoURL: xxx
      targetRevision: HEAD
      path: step-ca
      directory:
        exclude: "{values.yaml,step-ca-app.yaml}"

  destination:
    server: https://kubernetes.default.svc
    namespace: step-ca

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true