
persistence:
  enabled: true
  size: 2Gi
  storageClass: "longhorn"

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

existingSecrets:
  enabled: true
  ca: true
  certsAsSecret: true
  configAsSecret: false
  issuer: false
  sshHostCa: false
  sshUserCa: false

injectEnv:
  - name: STEP_UNATTENDED
    value: "true"

tools:
  enabled: false

bootstrap:
  enabled: false
  configmaps: false
  secrets: false

certificates:
  custom: true

injectCerts:
  enabled: false

extraVolumeMounts:
  - mountPath: /home/step/mis-certs
    name: certificados-eso
    readOnly: true

extraVolumes:
  - name: certificados-eso
    secret:
      secretName: step-ca-custom-certs

ca:
  password:
    existingSecret: manual-step-ca-password
  config:
    address: :9000
    insecureAddress: ""

    root: /home/step/certs/root_ca.crt
    crt: /home/step/certs/intermediate_ca.crt
    key: /home/step/secrets/intermediate_ca_key
    federatedRoots: null
    logger:
      format: text
    db:
      type: badgerv2
      dataSource: /home/step/db
      badgerFileLoadingMode: ""
    dnsNames:
      - xxx
      - step-ca-gitops-step-certificates.step-ca.svc.cluster.local
      - step-ca-gitops-step-certificates.step-ca.svc
      - step-ca-gitops-step-certificates
    tls:
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      minVersion: 1.2
      maxVersion: 1.3
      renegotiation: false
    authority:
      provisioners:
        - name: admin
          type: JWK
          key:
            use: sig
            kty: EC
            kid: xxx
            crv: P-256
            alg: ES256
            x: xxx
            "y": xxx
          encryptedKey: xxx
        - name: acme-internal
          type: ACME

profiles:
  defaults:
    ca-url: https://step-ca-gitops-step-certificates.step-ca.svc.cluster.local
    ca-config: /home/step/config/ca.json
    fingerprint: xxx
    root: /home/step/certs/root_ca.crt