apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-gitops
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.14.4
      helm:
        valueFiles:
          - $values/cert-manager/values.yaml

    - repoURL: https://gitlab.lst.tfo.upm.es/kubernetescore/aplicacionescore.git
      targetRevision: HEAD
      ref: values
      path: cert-manager

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true